"""empty message

Revision ID: 5150770f28fc
Revises: 625157d768d5
Create Date: 2022-07-08 20:02:21.041898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5150770f28fc'
down_revision = '625157d768d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_person')
    # ### end Alembic commands ###
